accessing
expectedException: anException
  expectedException := anException